# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - run: yarn
      - run: yarn build

  deploy_client:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - run: yarn
      - run: yarn build --scope client
      - run:
          name: Configure git client
          command: |
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME
      - run:
          name: Deploy the app to GitHub pages
          command: |
            npx gh-pages -m "[ci skip] auto deploy" -d client/build

  deploy_server:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - run:
          name: Synchronize front-end URL with the server
          command: |
            npx heroku config:set PUBLIC_URL=$PUBLIC_URL -a $HEROKU_APP_NAME
      - run:
          name: Deploy Master to Heroku
          command: |
            git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy_client:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy_server:
          requires:
            - build
          filters:
            branches:
              only: master
